### ISSUE TITLE
EPIC: Policy Distribution for KCP-Edge

### ISSUE THREAD

**Issue by clubanderson** [kcp-dev/edge-mc#54]
Work in progress for [Policy Distribution for KCP-Edge](https://docs.google.com/document/d/1lKIFfvWBIdzBoSoQTeMA8aqRb5d9hrnAOpQOjGIc5f8/edit?usp=sharing)

References

[Slides](https://ibm.box.com/s/ynmj394oeh1qq9kpgwy81a3wxmzv5q12) used in the https://github.com/kcp-dev/edge-mc/issues/44 on Dec. 1 ([recording](https://youtu.be/1GnwLRSEKP0))
[Demo recording](https://ibm.box.com/s/yvpiz03lwti6gvjpw5rqsfkzxak12c6e)
[Prototype Implementation](https://github.com/IBM/policy-control-operator)
Actions from comments in the Dec. 1. meeting

Review integration of OCM policy/Kyverno
Check [Policy Report](https://github.com/kubernetes-sigs/wg-policy-prototypes/blob/master/policy-report/README.md) and [Kubernetes Policy Management](https://github.com/kubernetes/sig-security/blob/main/sig-security-docs/papers/policy/kubernetes-policy-management.md)
Check the latest Upsync feature in KCP
Clarify cluster-scope sync requirement
CC: @yana1205

### Demo Steps

Successful demonstration will include consideration for 
- [ ] generic application of policy to a wide number of products/projects from CNCF (lead projects from Constantine)
- [ ] inclusion of policy reports from [Kubernetes Policy Management](https://github.com/kubernetes/sig-security/blob/main/sig-security-docs/papers/policy/kubernetes-policy-management.md) so that policy status is reported using OSCAL and other control formats, and be used in IBM's SCC, OCM or other security policy definition, security compliance, and posture monitoring and enforcement products.

### Action Items

- [X] Scope of the current demo is necessary to fit in the prototype boundaries
- [X] Contribute to the final demo script and recording

### Stories

- [x] #53
- [x] #55 
- [x] #56 
- [x] #57 

_No response_

**Comment by yuji-watanabe-jp** [comment]
comment

**Comment by clubanderson** [comment]
sub-issue #53

**Comment by clubanderson** [comment]
@cmadam I added the issues.

**Comment by yana1205** [comment]
Right, we are tracking this in the c2p work on KubeStellar. This can be closed.
